project:
  type: book

execute: 
  freeze: true

book:
  title: "Exercícios computacionais para GAAL"
  author: 
    - name: "Csaba Schneider"
    - affiliation: Universidade Federal de Minas Gerais
  date: "25 November 2024"
  chapters:
    - index.qmd
    - matrices.qmd
    - sistemas.qmd
    - interpol.qmd
    - geogebra.qmd
    - diagonal.qmd
license: "CC BY"
copyright: 
  holder: Csaba Schneider
  year: 2025
format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    fontsize: 12pt
    include-in-header:
      - file: macros.html
    grid:
      sidebar-width: 200px
      body-width: 800px
      margin-width: 600px
      gutter-width: 1.5rem
#  pdf:
#    include-in-header:
#      - file: "macros.tex"
